### ISSUE TITLE
[BUG REPORT] Link of github repo doesn't work

### ISSUE THREAD

**Issue by KendallDoesCoding** [krshdev/krshdev#16]
The link of the "Website" on this github repo is invalid as you changed you github username from "krishguptadev" to "krshdev"

Please update the url accordingly.

Thanks

**Comment by KendallDoesCoding** [comment]
Not what I was talking about but good you fixed that too. I was talking about this link in the repo:

![image](https://user-images.githubusercontent.com/84712013/154229260-8f5d2ff7-57e4-46b2-84cf-4da33b257e71.png)

Please reopen

**Comment by krshdev** [comment]
Fixed

**Comment by KendallDoesCoding** [comment]
> Fixed

thanks
